# -*- coding: utf-8 -*-
"""AutoBioStyleDatasetGeneration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_xHIWJ_Zl3oApfjPhdWOBJDOmR6UVdp
"""

# configs
base_directory = "AutobioLoraFinetuning"
OUTPUT_DIR = Path(f"{base_directory}/generated_images")
image_generator_path = "runwayml/stable-diffusion-v1-5" # HF or local path

import os
import sys
from google.colab import drive
import torch
from diffusers import StableDiffusionPipeline
from pathlib import Path

if not os.path.exists(local_link_path):
    os.symlink(gdrive_path, local_link_path)

sys.path.append(local_link_path)

# create out dir if necessary
OUTPUT_DIR.mkdir(exist_ok=True)

pipe = StableDiffusionPipeline.from_pretrained(
    image_generator_path,
    use_safetensors=True,
)
pipe = pipe.to("cuda")

# generate and save images for prompt
def generate_images(prompt, negative_prompt="worst quality", num_images=10, steps=20, seed=None):
    images = []
    generator = torch.Generator("cuda").manual_seed(seed) if seed is not None else None

    for i in range(num_images):
        img = pipe(prompt, num_inference_steps=steps, generator=generator, negative_prompt=negative_prompt).images[0]
        images.append(img)
        # Save image
        out_path = OUTPUT_DIR / f"{prompt.replace(' ', '_')}_{i+1}.png"
        img.save(out_path)
    return images


nouns = [
    "dog",
    "cat",
    "boy",
    "girl",
    "cow",
    "elephant",
    "fish",
    "doctor",
    "hero",
    "dragon"
]

verbs = [
    "running",
    "sitting",
    "eating",
    "sleeping",
    "jumping",
    "playing",
    "laughing",
    "drinking",
    "hiding",
    "chasing"
]

prompts_list = [f"best quality, clean, sketch stylized illustration {noun} that is {verb}" for noun in nouns for verb in verbs]
negative_prompt = "worst quality, bad quality, glitch, busy, messy, mistake"

# call generate_images for each prompt
for prompt in prompts_list:
    print(f"Generating images for prompt: {prompt}")
    generated_images = generate_images(prompt, negative_prompt=negative_prompt, num_images=3, steps=50)
    for img in generated_images:
        display(img)